# Generated by Django 6.0.2 on 2026-02-11 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PanchayatOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RTIRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('applicant_name', models.CharField(max_length=200)),
                ('date_filed', models.DateField()),
                ('subject', models.TextField()),
                ('panchayat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rti.panchayatoffice')),
            ],
        ),
        migrations.CreateModel(
            name='RTIResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.TextField()),
                ('date_replied', models.DateField()),
                ('is_delayed', models.BooleanField(default=False)),
                ('rti_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rti.rtirequest')),
            ],
        ),
        migrations.CreateModel(
            name='AnalystReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('COMPLETE', 'Complete Information'), ('VAGUE', 'Vague Reply'), ('DENIED', 'Information Denied'), ('DELAYED', 'Delayed Response')], max_length=20)),
                ('remarks', models.TextField()),
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rti.rtiresponse')),
            ],
        ),
    ]
