# Generated by Django 6.0.2 on 2026-02-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtirequest',
            name='acknowledgement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rtirequest',
            name='acknowledgement_document',
            field=models.FileField(blank=True, null=True, upload_to='rti/acknowledgements/'),
        ),
        migrations.AddField(
            model_name='rtirequest',
            name='original_application',
            field=models.FileField(blank=True, null=True, upload_to='rti/original/'),
        ),
        migrations.AddField(
            model_name='rtirequest',
            name='response_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rtirequest',
            name='response_document',
            field=models.FileField(blank=True, null=True, upload_to='rti/responses/'),
        ),
    ]
