# Generated by Django 6.0.2 on 2026-02-13 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rti', '0002_rtirequest_acknowledgement_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appeal_type', models.CharField(choices=[('FIRST', 'First Appeal'), ('SECOND', 'Second Appeal')], max_length=10)),
                ('reference_number', models.CharField(max_length=100)),
                ('date_filed', models.DateField()),
                ('request_pdf', models.FileField(upload_to='appeals/requests/')),
                ('response_pdf', models.FileField(blank=True, null=True, upload_to='appeals/responses/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
