# Generated by Django 6.0.2 on 2026-02-20 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rti', '0003_appeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='parent_appeal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rti.appeal'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='rti_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rti.rtirequest'),
        ),
    ]
