# Generated by Django 6.0.2 on 2026-02-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rti', '0004_appeal_parent_appeal_appeal_rti_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('DECIDED', 'Decided')], default='PENDING', max_length=20),
        ),
    ]
