# Generated by Django 6.0.2 on 2026-02-21 06:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rti', '0005_appeal_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=100)),
                ('date_filed', models.DateField(default=django.utils.timezone.now)),
                ('request_pdf', models.FileField(upload_to='appeals/first/request/')),
                ('response_pdf', models.FileField(blank=True, null=True, upload_to='appeals/first/response/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('DECIDED', 'Decided')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rti_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_appeals', to='rti.rtirequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecondAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=100)),
                ('date_filed', models.DateField(default=django.utils.timezone.now)),
                ('request_pdf', models.FileField(upload_to='appeals/second/request/')),
                ('response_pdf', models.FileField(blank=True, null=True, upload_to='appeals/second/response/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('DECIDED', 'Decided')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_appeal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='second_appeal', to='rti.firstappeal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Appeal',
        ),
    ]
